### ISSUE TITLE
Unable to access haskell-happstack via noaxiom.org

### ISSUE THREAD

**Issue by netlexer** [tensor5/haskell-happstack#15]
I've been getting an error for a few days now, I'm unable to update the package list. Pacman reports:

> % sudo pacman -Syyu
[snip]
error: failed retrieving file 'haskell-happstack.db' from noaxiom.org : Connection timed out after 10001 milliseconds
error: failed to update haskell-happstack (download library error)

My /etc/pacman.conf contains

> [haskell-happstack]
Server = http://noaxiom.org/$repo/$arch

which I believe is the correct stanza. 

Cheers.

**Comment by tensor5** [comment]
Should work now.

**Comment by netlexer** [comment]
Yes, it works fine now. Closing.
