### ISSUE TITLE
An extended diff with upstream cblrepo.db

### ISSUE THREAD

**Issue by nponeccop** [tensor5/haskell-happstack#9]
https://gist.github.com/nponeccop/94ad3aa0140634a287c9

It is modelled after `yaourt -Su`, but without colors and with two additional categories which should be empty until something bad happens to upstream:
```
==> Package upgrade only (new release):
haskell-core       GLUT                  2.5.1.1    4   ->  5
haskell-core       HTTP                  4000.2.19  2   ->  3
==> Software upgrade (new version):
haskell-core       JuicyPixels    3.1.7.1   5  ->  3.2.1     1
haskell-core       async          2.0.1.6   3  ->  2.0.2     1
haskell-core       auto-update    0.1.2     2  ->  0.1.2.1   1
==> Adopted packages (our RepoPkg in upstream)
haskell-core       appar       0.1.4     2  ->  0.1.4     1
haskell-happstack  fay         0.21.2.1  2  ->  0.21.2.1  7
haskell-happstack  fay-base    0.19.4.1  2  ->  0.19.4.1  9
==> Dropped packages (our DistroPkg not in upstream)
wai-extra   3.0.3  4
wai-logger  2.2.3  14
```
It's example output, `wai` isn't actually dropped from `core` :)

`/bin/printf` can be used instead of `column` to get consistent formatting across categories. And pacman -Sl can be used as version source instead of upstream `cblrepo.db` or in addition to them to provide extra sanity checks.

Feel free to put to `contrib/` if you don't find it useful for yourself.

**Comment by tensor5** [comment]
Maybe with a format change I could also use this script to generate commit messages.

**Comment by nponeccop** [comment]
I parse version control diffs of `cblrepo.db` for that. I use a very coarse approach of 

```
hg diff cblrepo.db | cut -c 1-77 | grep -vE "^([ @]|\+\+\+|---)" | \
    cut -d \" --output-delimiter=' ' -f 1,2,4,9
```
but `jshon` tool can be used for precise JSON parsing from shell if needed.
